# Generated by Django 3.2.9 on 2021-12-10 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='contraseña',
            field=models.CharField(default='PASSWORD', max_length=150),
        ),
        migrations.AddField(
            model_name='usuario',
            name='correo',
            field=models.CharField(default='EMAIL', max_length=150),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nombre_usuario',
            field=models.CharField(default='USERNAME', max_length=150),
        ),
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.CharField(default='ROL', max_length=150),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
