# Generated by Django 3.2.9 on 2021-12-18 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='categoria',
            field=models.CharField(choices=[('1', 'FIN DE LA POBREZA'), ('2', 'HAMBRE CERO'), ('3', 'SALUD Y BIENESTAR'), ('4', 'EDUCADION DE CALIDAD'), ('5', 'IGUALDAD DE GENERO'), ('6', 'AGUA LIMPIA Y SANEAMIENTO'), ('7', 'ENERGIA'), ('8', 'CRECIMIENTO ECONOMICO'), ('9', 'AGUA'), ('10', 'REDUCCION DE DESIGUALDADES'), ('11', 'COMUNIDADES SOSTENIBLES'), ('12', 'PRODUCCION Y CONSUMO'), ('13', 'ACCION POR EL CLIMA'), ('14', 'VIDA SUBMARINA'), ('15', 'ECOSISTEMAS TERRESTRES'), ('16', 'PAZ, JUSTICIA'), ('17', 'ALIANZAS')], default='1', max_length=10),
        ),
    ]
